# fly.toml file generated for ckreiling-blog-wordpress on 2023-03-29T18:10:41-04:00

app = "ckreiling-blog-wordpress"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "wordpress:6.1.1-apache"

[deploy]
  strategy = "immediate"

[mounts]
  source = "ckreiling_wp_data"
  destination = "/var/www/html"

[env]
  WORDPRESS_DB_HOST = "ckreiling-blog-mysql.internal"
  WORDPRESS_DB_USER = "wp_user"
  WORDPRESS_DB_NAME = "wp_db"
  # Enable debugging
  # WORDPRESS_DEBUG = "1"
  WORDPRESS_CONFIG_EXTRA = """
define('WP_SITEURL', 'https://ckreiling.dev');
define('WP_AUTO_UPDATE_CORE', false);
"""

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
