app = "ckreiling-blog-mysql"
kill_signal = "SIGINT"
kill_timeout = 5

[mounts]
  source="ckreiling_blog_mysql_data"
  destination="/data"

[env]
  MYSQL_DATABASE = "wp_db"
  MYSQL_USER = "wp_user"

[build]
  image = "mysql:5"

[experimental]
  cmd = [
    "--default-authentication-plugin",
    "mysql_native_password",
    "--datadir",
    "/data/mysql"
  ]

