# fly.toml file generated for ckreiling-blog-mysql on 2023-03-29T20:30:37-04:00

app = "ckreiling-blog-mysql"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[env]
  MYSQL_DATABASE = "wp_db"
  MYSQL_USER = "wp_user"

[mounts]
  source = "ckreiling_blog_mysql_data"
  destination = "/data"

